### ISSUE TITLE
How to change code to classify the whole picture？

### ISSUE THREAD

**Issue by forestbat** [cjaca/Hyperspectral-Image-Analysis#1]
I want to classify the whole remote sensing picture not reference pixel，so I changed code：
```
    raster = rasterio.open(img_path, 'r')
    arr = raster.read()
    ref_count = 1
    ref_cord = [[round(arr.shape[1]), round(arr.shape[2])]]
    ……
    # ref_vect is reference pixel
    ref_vect = [[0 for x in range(bands)] for y in range(ref_count)]
    for i in range(ref_count):
        for j in range(bands):
            ref_vect[i][j] = arr[j, int(ref_cord[i][0])-1, int(ref_cord[i][1])-1]
```
But when I run the code，`ref_vect` is `[[0, 0, 0, 0]]` and `r = ref_vect[j][nb]` is all 0，so classified picture is all black.
How to specify ref_count，ref_cord and other variables to make the program work normally？

**Comment by cjaca** [comment]
Hi,
The algorithm itself is analyzing all 2d layers of the multilayer picture, not only one pixel.
Could you please elaborate more on what remote sensing picture do you have, or upload it here?

**Comment by forestbat** [comment]
[GF_6.zip](https://github.com/cjaca/Hyperspectral-Image-Analysis/files/14853524/GF_6.zip)
Thank you for your reply.
This picture come from GaoFen-1 satellite，and it has 4 bands.

**Comment by forestbat** [comment]
3 days passed，do you have answer of the problem？

**Comment by cjaca** [comment]
Hi, I understand the problem now. I need some time to make it work, since it's not my daily business topic. I will notify you once It will be ready solution to analyze without reference pixels for less amount of layers

**Comment by lazyn1997** [comment]
Your image has a black edge, all the channel values are 0, ref_vect is correct, and then the following formula will give the nan value, which does not satisfy the if condition, so it is classified to the background value, and the whole image is black.
![image](https://github.com/cjaca/Hyperspectral-Image-Analysis/assets/34644177/58e85438-287e-485a-b6b7-ec79b49719bb)
You can get the following classification by `arr = numpy.where(arr <= 0, 1e-6, arr)` setting the arr ≤0 to a minimal value.
![image](https://github.com/cjaca/Hyperspectral-Image-Analysis/assets/34644177/cdafb330-7293-4abc-8921-ff135c3e8a28)

**Comment by cjaca** [comment]
Change merged to master branch.
Thanks for fixing this issue.
